title: OpenAhmedabad
email: jayesh.gohel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Let's make Ahmedabad Great again!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jayeshgohel
github_username:  gnatih
repository: DatameetAMD/openahmedabad.org

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
